### ISSUE TITLE
Create AWS online site or VM appliance for easy access to OntoGraph

### ISSUE THREAD

**Issue by NinePts** [NinePts/OntoGraph#23]

**Comment by NinePts** [comment]
Problem with a VM appliance is the bundling of the Stardog software. Whether this is possible/legal is an issue.

An AWS instance (running Stardog and OntoGraph) was previously available, but was taken down to cut on-going expenses. Other funding options may be available.

**Comment by NinePts** [comment]
Created a VM hosting OntoGraph and Stardog at http://45.76.26.91:8181.

**Comment by seralf** [comment]
Hi I've recently discovered the project and I'd like to test/evaluate it for internal usage in my team.
The online application is currently down: are there plans to republish it or the best option is to install the server locally?
